source ~/.vim/plugins.vim

" Section General {{{

set nocompatible   " Use vim settings, rather then vi settings
set autoread       " detect when a file is changed

filetype indent plugin on
syntax on

set clipboard:unnamed

" }}}

" Section Theme and colors {{{

" Themes and colors

if filereadable(expand("~/.vimrc_background"))
  let base16colorspace=256
  source ~/.vimrc_background
endif

" make comments and HTML attributes italic
highlight Comment cterm=italic
highlight htmlArg cterm=italic
highlight xmlAttrib cterm=italic

highlight Search ctermfg=black
" Fix until https://github.com/chriskempson/base16-vim/issues/125
highlight Error ctermfg=white
highlight Error ctermbg=red
highlight MatchParen ctermbg=blue ctermfg=white guibg=NONE guifg=#00ff00 cterm=BOLD gui=BOLD

" Tabs and other special chars
highlight SpecialKey ctermbg=none ctermfg=241
highlight NonText ctermbg=none ctermfg=241

set highlight+=N:DiffText             " make current line number stand out a little
"set highlight+=c:LineNr               " blend vertical separators with line numbers

" Vim airline
let g:airline_powerline_fonts = 1
let g:airline_theme='base16'
" Always show statusline
set laststatus=2

"}}}

" Editor behaviour {{{

set updatecount=80                    " update swapfiles every 80 typed chars
set updatetime=2000                   " same as YCM

" Buffers
set hidden   " allows you to hide buffers with unsaved changes
" Open quickfix in verticsl
autocmd filetype qf wincmd J

" Reload modified files
set autoread

" }}}

" Section Editor UI {{{

" Brackets
set showmatch
set mat=2

" Cursor
set cursorline

" Editing
set backspace=indent,eol,start

" Error Bells
set visualbell

" Folds
set foldmethod=syntax       " fold based on indent
set foldnestmax=10          " deepest fold is 10 levels
set nofoldenable            " don't fold by default
set foldlevel=1

" Indent
set autoindent
set smartindent

" Line Numbers
set relativenumber      " Show relative number
set number
set numberwidth=4

if has('mouse')
	set mouse=a
	" set ttymouse=xterm2
endif

" Menu
set noshowmode
set wildmenu
set wildmode=list:longest,full

" Meta
set shortmess+=I                      " no splash screen

" Scroll
set scrolloff=5 " Always lead with n lines

" Splits
if has('windows')
  set splitbelow " open horizontal splits below current window
endif

if has('vertsplit')
  set splitright    " open vertical splits to the right of the current window
endif

" Tabs
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" Whitespace
set list
set listchars=tab:▸\ ,eol:¬,trail:·

" Wrap
set nowrap
set textwidth=80
set formatoptions=qrn1
"set colorcolumn=80
execute "set colorcolumn=" . join(range(80,335), ',')

" }}}

" Section Mappings {{{

" change the mapleader from \ to ,
let mapleader=","

" Map ; to :
nnoremap ; :

" Reload vim config
nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <leader>sv :so $MYVIMRC<CR>

" Better split
nnoremap <leader>w <C-w>v<C-w>l
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Folds
noremap <space> za

" Move lines
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
inoremap <A-j> <Esc>:m .+1<CR>==gi
inoremap <A-k> <Esc>:m .-2<CR>==gi
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv

" Fuck myself hard
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
" (comment for not that hard)
"inoremap <up> <nop>
"inoremap <down> <nop>
"inoremap <left> <nop>
"inoremap <right> <nop>

" }}}

" Section Plugins {{{

" Toggle NERDTree
nmap <silent> <leader>k :NERDTreeToggle<cr>
" expand to the path of the file in the current buffer
nmap <silent> <leader>y :NERDTreeFind<cr>

" Load vimtree on empty Vim
"autocmd StdinReadPre * let s:std_in=1
"autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" Close vim if only has nerdtree
" autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

let loaded_netrwPlugin=1           
let NERDTreeShowHidden=1
let NERDTreeDirArrowExpandable = '▷'
let NERDTreeDirArrowCollapsible = '▼'
let NERDTreeRespectWildIgnore=1

let g:webdevicons_conceal_nerdtree_brackets = 1
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
" after a re-source, fix syntax matching issues (concealing brackets):
if exists('g:loaded_webdevicons')
    call webdevicons#refresh()
endif

" FZF
nmap <silent> <leader>f :FZF<cr>

let g:fzf_nvim_statusline = 0
let g:fzf_layout = { 'down': '~25%' }

" ale
let g:ale_sign_error = '=>'
let g:ale_sign_warning = '->'

" Not until integrated with tsuquyomi
let g:ale_set_quickfix = 1
let g:ale_lint_on_text_changed = 'never'


let g:ale_linters = {
\   'python': ['flake8', 'pylint'],
\}

" Typescript js string templates
autocmd FileType typescript JsPreTmpl html
autocmd FileType typescript syn clear foldBraces 

" Deoplete
let g:deoplete#enable_at_startup = 1
let g:SuperTabDefaultCompletionType = "<c-x><c-o>"

" Emmet
autocmd FileType html,css,js,ts EmmetInstall
" }}}

" vim:foldmethod=marker:foldlevel=0
" vim:syntax=vim
