export DOTFILES=$HOME/.dotfiles
export ZSH_FILES=$DOTFILES/zsh


# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh


# adding path directory for custom scripts
export PATH=$DOTFILES/bin:$PATH
export PATH=$PATH:"/Applications/Visual Studio Code.app/Contents/Resources/app/bin"


#source all .zsh files inside of the zsh/ directory
for config ($ZSH_FILES/**/*.zsh) source $config


# Color Scheme
color tomorrow-night
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"


DEFAULT_USER="jarias"


# OhMYZSH options
plugins=(brew docker git git-flow ng node npm osx python \
         sbt scw scala tmux vi-mode z zsh-syntax-highlighting) 


source $ZSH/oh-my-zsh.sh


# Fix Autocomplete
# start typing + [Up-Arrow] - fuzzy find history forward
if [[ "${terminfo[kcuu1]}" != "" ]]; then
  autoload -U up-line-or-beginning-search
  zle -N up-line-or-beginning-search
  bindkey "${terminfo[kcuu1]}" up-line-or-beginning-search
fi
# start typing + [Down-Arrow] - fuzzy find history backward
if [[ "${terminfo[kcud1]}" != "" ]]; then
  autoload -U down-line-or-beginning-search
  zle -N down-line-or-beginning-search
  bindkey "${terminfo[kcud1]}" down-line-or-beginning-search
fi


# Fix Backspace mapping in vim mode
bindkey "^[[3~" delete-char
bindkey -a "^[[3~" delete-char


# User configuration
export EDITOR='vim'
export GIT_EDITOR='vim'


# Fuzzy finder configuration
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='ag -g ""'
