echo "\n\nInstalling extensions"
code --install-extension Angular.ng-template
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension daltonjorge.scala
code --install-extension dbaeumer.vscode-eslint
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension jakethashi.vscode-angular2-emmet
code --install-extension James-Yu.latex-workshop
code --install-extension johnpapa.angular-essentials
code --install-extension johnpapa.Angular2
code --install-extension johnpapa.winteriscoming
code --install-extension mechatroner.rainbow-csv
code --install-extension Mikael.Angular-BeastCode
code --install-extension ms-python.python
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension natewallace.angular2-inline
code --install-extension npxms.hide-gitignored
code --install-extension PeterJausovec.vscode-docker
code --install-extension PKief.material-icon-theme
code --install-extension redhat.vscode-yaml
code --install-extension robertohuertasm.vscode-icons
code --install-extension shyykoserhiy.vscode-spotify
code --install-extension sidneys1.gitconfig
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-spanish
code --install-extension vscodevim.vim
code --install-extension wix.vscode-import-cost
